runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

env_variables:
  INSTANCE_CONNECTION_NAME: "magichack-167504:us-central1:magichack"
  CLOUD_SQL_USER: "root"
